version: "3"
services:

  mysql:
    image: mysql:8.0.36
    # image: mysql:5.7.42
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
      - ./mysql/log:/var/log/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234567890032password"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis.conf:ro
      - ./redis/data:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "Asia/Shanghai"

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "127.0.0.1:11211:11211"
    environment:
       MEMCACHED_CACHE_SIZE: "128"
